### ISSUE TITLE
Broken link for the Kompas3D

### ISSUE THREAD

**Issue by sviatoslav-gusev** [alealexpro100/ru-school-scoop#2]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
Installing 'kompas-study-np' (20) [64bit] from ru-school-scoop bucket
The remote server returned an error: (429) Too Many Requests.
URL https://s10887.cdn.ngenix.net/download/26EB9B75D172520E54FEFD1BADF2E19BED4AB7E1C7139655BDB3C3E27EEAF1AA9534B640C00B03159BEDD31F67A94B4D210D4DB93F17A0624A4B439F354DB1DB/KOMPAS/v20_Edu/x64/KOMPAS-3D_v20_Study_x64.zip#/dl.7z is not valid
```

**Comment by alealexpro100** [comment]
Should be fixed with https://github.com/alealexpro100/ru-school-scoop/commit/4688fd0b38c74f66ecb141f32d91bd8632a8b216. Version v21 will be uploaded soon.

**Comment by sviatoslav-gusev** [comment]
Thanks, V20 installs successfully!
V21 has checksum issue which is described in another case
